
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `WorkOrder` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model WorkOrder
 * 
 */
export type WorkOrderModel = runtime.Types.Result.DefaultSelection<Prisma.$WorkOrderPayload>

export type AggregateWorkOrder = {
  _count: WorkOrderCountAggregateOutputType | null
  _avg: WorkOrderAvgAggregateOutputType | null
  _sum: WorkOrderSumAggregateOutputType | null
  _min: WorkOrderMinAggregateOutputType | null
  _max: WorkOrderMaxAggregateOutputType | null
}

export type WorkOrderAvgAggregateOutputType = {
  id: number | null
  pasajeros: number | null
  combustible: number | null
  hielo: number | null
  aguaBebidas: number | null
  gastoVarios: number | null
  pagoCapitana: number | null
  pagoMarinero: number | null
  costoTotal: number | null
  deposito: number | null
  saldoCliente: number | null
}

export type WorkOrderSumAggregateOutputType = {
  id: number | null
  pasajeros: number | null
  combustible: number | null
  hielo: number | null
  aguaBebidas: number | null
  gastoVarios: number | null
  pagoCapitana: number | null
  pagoMarinero: number | null
  costoTotal: number | null
  deposito: number | null
  saldoCliente: number | null
}

export type WorkOrderMinAggregateOutputType = {
  id: number | null
  createdAt: Date | null
  nombre: string | null
  fecha: Date | null
  horaSalida: string | null
  destino: string | null
  puntoEncuentro: string | null
  pasajeros: number | null
  detallesNotas: string | null
  combustible: number | null
  hielo: number | null
  aguaBebidas: number | null
  gastoVarios: number | null
  pagoCapitana: number | null
  pagoMarinero: number | null
  costoTotal: number | null
  deposito: number | null
  saldoCliente: number | null
}

export type WorkOrderMaxAggregateOutputType = {
  id: number | null
  createdAt: Date | null
  nombre: string | null
  fecha: Date | null
  horaSalida: string | null
  destino: string | null
  puntoEncuentro: string | null
  pasajeros: number | null
  detallesNotas: string | null
  combustible: number | null
  hielo: number | null
  aguaBebidas: number | null
  gastoVarios: number | null
  pagoCapitana: number | null
  pagoMarinero: number | null
  costoTotal: number | null
  deposito: number | null
  saldoCliente: number | null
}

export type WorkOrderCountAggregateOutputType = {
  id: number
  createdAt: number
  nombre: number
  fecha: number
  horaSalida: number
  destino: number
  puntoEncuentro: number
  pasajeros: number
  detallesNotas: number
  combustible: number
  hielo: number
  aguaBebidas: number
  gastoVarios: number
  pagoCapitana: number
  pagoMarinero: number
  costoTotal: number
  deposito: number
  saldoCliente: number
  _all: number
}


export type WorkOrderAvgAggregateInputType = {
  id?: true
  pasajeros?: true
  combustible?: true
  hielo?: true
  aguaBebidas?: true
  gastoVarios?: true
  pagoCapitana?: true
  pagoMarinero?: true
  costoTotal?: true
  deposito?: true
  saldoCliente?: true
}

export type WorkOrderSumAggregateInputType = {
  id?: true
  pasajeros?: true
  combustible?: true
  hielo?: true
  aguaBebidas?: true
  gastoVarios?: true
  pagoCapitana?: true
  pagoMarinero?: true
  costoTotal?: true
  deposito?: true
  saldoCliente?: true
}

export type WorkOrderMinAggregateInputType = {
  id?: true
  createdAt?: true
  nombre?: true
  fecha?: true
  horaSalida?: true
  destino?: true
  puntoEncuentro?: true
  pasajeros?: true
  detallesNotas?: true
  combustible?: true
  hielo?: true
  aguaBebidas?: true
  gastoVarios?: true
  pagoCapitana?: true
  pagoMarinero?: true
  costoTotal?: true
  deposito?: true
  saldoCliente?: true
}

export type WorkOrderMaxAggregateInputType = {
  id?: true
  createdAt?: true
  nombre?: true
  fecha?: true
  horaSalida?: true
  destino?: true
  puntoEncuentro?: true
  pasajeros?: true
  detallesNotas?: true
  combustible?: true
  hielo?: true
  aguaBebidas?: true
  gastoVarios?: true
  pagoCapitana?: true
  pagoMarinero?: true
  costoTotal?: true
  deposito?: true
  saldoCliente?: true
}

export type WorkOrderCountAggregateInputType = {
  id?: true
  createdAt?: true
  nombre?: true
  fecha?: true
  horaSalida?: true
  destino?: true
  puntoEncuentro?: true
  pasajeros?: true
  detallesNotas?: true
  combustible?: true
  hielo?: true
  aguaBebidas?: true
  gastoVarios?: true
  pagoCapitana?: true
  pagoMarinero?: true
  costoTotal?: true
  deposito?: true
  saldoCliente?: true
  _all?: true
}

export type WorkOrderAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorkOrder to aggregate.
   */
  where?: Prisma.WorkOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkOrders to fetch.
   */
  orderBy?: Prisma.WorkOrderOrderByWithRelationInput | Prisma.WorkOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.WorkOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkOrders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned WorkOrders
  **/
  _count?: true | WorkOrderCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: WorkOrderAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: WorkOrderSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: WorkOrderMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: WorkOrderMaxAggregateInputType
}

export type GetWorkOrderAggregateType<T extends WorkOrderAggregateArgs> = {
      [P in keyof T & keyof AggregateWorkOrder]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWorkOrder[P]>
    : Prisma.GetScalarType<T[P], AggregateWorkOrder[P]>
}




export type WorkOrderGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WorkOrderWhereInput
  orderBy?: Prisma.WorkOrderOrderByWithAggregationInput | Prisma.WorkOrderOrderByWithAggregationInput[]
  by: Prisma.WorkOrderScalarFieldEnum[] | Prisma.WorkOrderScalarFieldEnum
  having?: Prisma.WorkOrderScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WorkOrderCountAggregateInputType | true
  _avg?: WorkOrderAvgAggregateInputType
  _sum?: WorkOrderSumAggregateInputType
  _min?: WorkOrderMinAggregateInputType
  _max?: WorkOrderMaxAggregateInputType
}

export type WorkOrderGroupByOutputType = {
  id: number
  createdAt: Date
  nombre: string
  fecha: Date
  horaSalida: string
  destino: string
  puntoEncuentro: string
  pasajeros: number
  detallesNotas: string | null
  combustible: number | null
  hielo: number | null
  aguaBebidas: number | null
  gastoVarios: number | null
  pagoCapitana: number | null
  pagoMarinero: number | null
  costoTotal: number
  deposito: number
  saldoCliente: number
  _count: WorkOrderCountAggregateOutputType | null
  _avg: WorkOrderAvgAggregateOutputType | null
  _sum: WorkOrderSumAggregateOutputType | null
  _min: WorkOrderMinAggregateOutputType | null
  _max: WorkOrderMaxAggregateOutputType | null
}

type GetWorkOrderGroupByPayload<T extends WorkOrderGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<WorkOrderGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof WorkOrderGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WorkOrderGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WorkOrderGroupByOutputType[P]>
      }
    >
  >



export type WorkOrderWhereInput = {
  AND?: Prisma.WorkOrderWhereInput | Prisma.WorkOrderWhereInput[]
  OR?: Prisma.WorkOrderWhereInput[]
  NOT?: Prisma.WorkOrderWhereInput | Prisma.WorkOrderWhereInput[]
  id?: Prisma.IntFilter<"WorkOrder"> | number
  createdAt?: Prisma.DateTimeFilter<"WorkOrder"> | Date | string
  nombre?: Prisma.StringFilter<"WorkOrder"> | string
  fecha?: Prisma.DateTimeFilter<"WorkOrder"> | Date | string
  horaSalida?: Prisma.StringFilter<"WorkOrder"> | string
  destino?: Prisma.StringFilter<"WorkOrder"> | string
  puntoEncuentro?: Prisma.StringFilter<"WorkOrder"> | string
  pasajeros?: Prisma.IntFilter<"WorkOrder"> | number
  detallesNotas?: Prisma.StringNullableFilter<"WorkOrder"> | string | null
  combustible?: Prisma.FloatNullableFilter<"WorkOrder"> | number | null
  hielo?: Prisma.FloatNullableFilter<"WorkOrder"> | number | null
  aguaBebidas?: Prisma.FloatNullableFilter<"WorkOrder"> | number | null
  gastoVarios?: Prisma.FloatNullableFilter<"WorkOrder"> | number | null
  pagoCapitana?: Prisma.FloatNullableFilter<"WorkOrder"> | number | null
  pagoMarinero?: Prisma.FloatNullableFilter<"WorkOrder"> | number | null
  costoTotal?: Prisma.FloatFilter<"WorkOrder"> | number
  deposito?: Prisma.FloatFilter<"WorkOrder"> | number
  saldoCliente?: Prisma.FloatFilter<"WorkOrder"> | number
  receipts?: Prisma.ReceiptListRelationFilter
}

export type WorkOrderOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  fecha?: Prisma.SortOrder
  horaSalida?: Prisma.SortOrder
  destino?: Prisma.SortOrder
  puntoEncuentro?: Prisma.SortOrder
  pasajeros?: Prisma.SortOrder
  detallesNotas?: Prisma.SortOrderInput | Prisma.SortOrder
  combustible?: Prisma.SortOrderInput | Prisma.SortOrder
  hielo?: Prisma.SortOrderInput | Prisma.SortOrder
  aguaBebidas?: Prisma.SortOrderInput | Prisma.SortOrder
  gastoVarios?: Prisma.SortOrderInput | Prisma.SortOrder
  pagoCapitana?: Prisma.SortOrderInput | Prisma.SortOrder
  pagoMarinero?: Prisma.SortOrderInput | Prisma.SortOrder
  costoTotal?: Prisma.SortOrder
  deposito?: Prisma.SortOrder
  saldoCliente?: Prisma.SortOrder
  receipts?: Prisma.ReceiptOrderByRelationAggregateInput
}

export type WorkOrderWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.WorkOrderWhereInput | Prisma.WorkOrderWhereInput[]
  OR?: Prisma.WorkOrderWhereInput[]
  NOT?: Prisma.WorkOrderWhereInput | Prisma.WorkOrderWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"WorkOrder"> | Date | string
  nombre?: Prisma.StringFilter<"WorkOrder"> | string
  fecha?: Prisma.DateTimeFilter<"WorkOrder"> | Date | string
  horaSalida?: Prisma.StringFilter<"WorkOrder"> | string
  destino?: Prisma.StringFilter<"WorkOrder"> | string
  puntoEncuentro?: Prisma.StringFilter<"WorkOrder"> | string
  pasajeros?: Prisma.IntFilter<"WorkOrder"> | number
  detallesNotas?: Prisma.StringNullableFilter<"WorkOrder"> | string | null
  combustible?: Prisma.FloatNullableFilter<"WorkOrder"> | number | null
  hielo?: Prisma.FloatNullableFilter<"WorkOrder"> | number | null
  aguaBebidas?: Prisma.FloatNullableFilter<"WorkOrder"> | number | null
  gastoVarios?: Prisma.FloatNullableFilter<"WorkOrder"> | number | null
  pagoCapitana?: Prisma.FloatNullableFilter<"WorkOrder"> | number | null
  pagoMarinero?: Prisma.FloatNullableFilter<"WorkOrder"> | number | null
  costoTotal?: Prisma.FloatFilter<"WorkOrder"> | number
  deposito?: Prisma.FloatFilter<"WorkOrder"> | number
  saldoCliente?: Prisma.FloatFilter<"WorkOrder"> | number
  receipts?: Prisma.ReceiptListRelationFilter
}, "id">

export type WorkOrderOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  fecha?: Prisma.SortOrder
  horaSalida?: Prisma.SortOrder
  destino?: Prisma.SortOrder
  puntoEncuentro?: Prisma.SortOrder
  pasajeros?: Prisma.SortOrder
  detallesNotas?: Prisma.SortOrderInput | Prisma.SortOrder
  combustible?: Prisma.SortOrderInput | Prisma.SortOrder
  hielo?: Prisma.SortOrderInput | Prisma.SortOrder
  aguaBebidas?: Prisma.SortOrderInput | Prisma.SortOrder
  gastoVarios?: Prisma.SortOrderInput | Prisma.SortOrder
  pagoCapitana?: Prisma.SortOrderInput | Prisma.SortOrder
  pagoMarinero?: Prisma.SortOrderInput | Prisma.SortOrder
  costoTotal?: Prisma.SortOrder
  deposito?: Prisma.SortOrder
  saldoCliente?: Prisma.SortOrder
  _count?: Prisma.WorkOrderCountOrderByAggregateInput
  _avg?: Prisma.WorkOrderAvgOrderByAggregateInput
  _max?: Prisma.WorkOrderMaxOrderByAggregateInput
  _min?: Prisma.WorkOrderMinOrderByAggregateInput
  _sum?: Prisma.WorkOrderSumOrderByAggregateInput
}

export type WorkOrderScalarWhereWithAggregatesInput = {
  AND?: Prisma.WorkOrderScalarWhereWithAggregatesInput | Prisma.WorkOrderScalarWhereWithAggregatesInput[]
  OR?: Prisma.WorkOrderScalarWhereWithAggregatesInput[]
  NOT?: Prisma.WorkOrderScalarWhereWithAggregatesInput | Prisma.WorkOrderScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"WorkOrder"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"WorkOrder"> | Date | string
  nombre?: Prisma.StringWithAggregatesFilter<"WorkOrder"> | string
  fecha?: Prisma.DateTimeWithAggregatesFilter<"WorkOrder"> | Date | string
  horaSalida?: Prisma.StringWithAggregatesFilter<"WorkOrder"> | string
  destino?: Prisma.StringWithAggregatesFilter<"WorkOrder"> | string
  puntoEncuentro?: Prisma.StringWithAggregatesFilter<"WorkOrder"> | string
  pasajeros?: Prisma.IntWithAggregatesFilter<"WorkOrder"> | number
  detallesNotas?: Prisma.StringNullableWithAggregatesFilter<"WorkOrder"> | string | null
  combustible?: Prisma.FloatNullableWithAggregatesFilter<"WorkOrder"> | number | null
  hielo?: Prisma.FloatNullableWithAggregatesFilter<"WorkOrder"> | number | null
  aguaBebidas?: Prisma.FloatNullableWithAggregatesFilter<"WorkOrder"> | number | null
  gastoVarios?: Prisma.FloatNullableWithAggregatesFilter<"WorkOrder"> | number | null
  pagoCapitana?: Prisma.FloatNullableWithAggregatesFilter<"WorkOrder"> | number | null
  pagoMarinero?: Prisma.FloatNullableWithAggregatesFilter<"WorkOrder"> | number | null
  costoTotal?: Prisma.FloatWithAggregatesFilter<"WorkOrder"> | number
  deposito?: Prisma.FloatWithAggregatesFilter<"WorkOrder"> | number
  saldoCliente?: Prisma.FloatWithAggregatesFilter<"WorkOrder"> | number
}

export type WorkOrderCreateInput = {
  createdAt?: Date | string
  nombre: string
  fecha: Date | string
  horaSalida: string
  destino: string
  puntoEncuentro: string
  pasajeros: number
  detallesNotas?: string | null
  combustible?: number | null
  hielo?: number | null
  aguaBebidas?: number | null
  gastoVarios?: number | null
  pagoCapitana?: number | null
  pagoMarinero?: number | null
  costoTotal: number
  deposito?: number
  saldoCliente: number
  receipts?: Prisma.ReceiptCreateNestedManyWithoutWorkOrderInput
}

export type WorkOrderUncheckedCreateInput = {
  id?: number
  createdAt?: Date | string
  nombre: string
  fecha: Date | string
  horaSalida: string
  destino: string
  puntoEncuentro: string
  pasajeros: number
  detallesNotas?: string | null
  combustible?: number | null
  hielo?: number | null
  aguaBebidas?: number | null
  gastoVarios?: number | null
  pagoCapitana?: number | null
  pagoMarinero?: number | null
  costoTotal: number
  deposito?: number
  saldoCliente: number
  receipts?: Prisma.ReceiptUncheckedCreateNestedManyWithoutWorkOrderInput
}

export type WorkOrderUpdateInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  fecha?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  horaSalida?: Prisma.StringFieldUpdateOperationsInput | string
  destino?: Prisma.StringFieldUpdateOperationsInput | string
  puntoEncuentro?: Prisma.StringFieldUpdateOperationsInput | string
  pasajeros?: Prisma.IntFieldUpdateOperationsInput | number
  detallesNotas?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  combustible?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  hielo?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  aguaBebidas?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  gastoVarios?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  pagoCapitana?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  pagoMarinero?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  costoTotal?: Prisma.FloatFieldUpdateOperationsInput | number
  deposito?: Prisma.FloatFieldUpdateOperationsInput | number
  saldoCliente?: Prisma.FloatFieldUpdateOperationsInput | number
  receipts?: Prisma.ReceiptUpdateManyWithoutWorkOrderNestedInput
}

export type WorkOrderUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  fecha?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  horaSalida?: Prisma.StringFieldUpdateOperationsInput | string
  destino?: Prisma.StringFieldUpdateOperationsInput | string
  puntoEncuentro?: Prisma.StringFieldUpdateOperationsInput | string
  pasajeros?: Prisma.IntFieldUpdateOperationsInput | number
  detallesNotas?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  combustible?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  hielo?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  aguaBebidas?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  gastoVarios?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  pagoCapitana?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  pagoMarinero?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  costoTotal?: Prisma.FloatFieldUpdateOperationsInput | number
  deposito?: Prisma.FloatFieldUpdateOperationsInput | number
  saldoCliente?: Prisma.FloatFieldUpdateOperationsInput | number
  receipts?: Prisma.ReceiptUncheckedUpdateManyWithoutWorkOrderNestedInput
}

export type WorkOrderCreateManyInput = {
  id?: number
  createdAt?: Date | string
  nombre: string
  fecha: Date | string
  horaSalida: string
  destino: string
  puntoEncuentro: string
  pasajeros: number
  detallesNotas?: string | null
  combustible?: number | null
  hielo?: number | null
  aguaBebidas?: number | null
  gastoVarios?: number | null
  pagoCapitana?: number | null
  pagoMarinero?: number | null
  costoTotal: number
  deposito?: number
  saldoCliente: number
}

export type WorkOrderUpdateManyMutationInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  fecha?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  horaSalida?: Prisma.StringFieldUpdateOperationsInput | string
  destino?: Prisma.StringFieldUpdateOperationsInput | string
  puntoEncuentro?: Prisma.StringFieldUpdateOperationsInput | string
  pasajeros?: Prisma.IntFieldUpdateOperationsInput | number
  detallesNotas?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  combustible?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  hielo?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  aguaBebidas?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  gastoVarios?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  pagoCapitana?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  pagoMarinero?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  costoTotal?: Prisma.FloatFieldUpdateOperationsInput | number
  deposito?: Prisma.FloatFieldUpdateOperationsInput | number
  saldoCliente?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type WorkOrderUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  fecha?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  horaSalida?: Prisma.StringFieldUpdateOperationsInput | string
  destino?: Prisma.StringFieldUpdateOperationsInput | string
  puntoEncuentro?: Prisma.StringFieldUpdateOperationsInput | string
  pasajeros?: Prisma.IntFieldUpdateOperationsInput | number
  detallesNotas?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  combustible?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  hielo?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  aguaBebidas?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  gastoVarios?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  pagoCapitana?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  pagoMarinero?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  costoTotal?: Prisma.FloatFieldUpdateOperationsInput | number
  deposito?: Prisma.FloatFieldUpdateOperationsInput | number
  saldoCliente?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type WorkOrderCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  fecha?: Prisma.SortOrder
  horaSalida?: Prisma.SortOrder
  destino?: Prisma.SortOrder
  puntoEncuentro?: Prisma.SortOrder
  pasajeros?: Prisma.SortOrder
  detallesNotas?: Prisma.SortOrder
  combustible?: Prisma.SortOrder
  hielo?: Prisma.SortOrder
  aguaBebidas?: Prisma.SortOrder
  gastoVarios?: Prisma.SortOrder
  pagoCapitana?: Prisma.SortOrder
  pagoMarinero?: Prisma.SortOrder
  costoTotal?: Prisma.SortOrder
  deposito?: Prisma.SortOrder
  saldoCliente?: Prisma.SortOrder
}

export type WorkOrderAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pasajeros?: Prisma.SortOrder
  combustible?: Prisma.SortOrder
  hielo?: Prisma.SortOrder
  aguaBebidas?: Prisma.SortOrder
  gastoVarios?: Prisma.SortOrder
  pagoCapitana?: Prisma.SortOrder
  pagoMarinero?: Prisma.SortOrder
  costoTotal?: Prisma.SortOrder
  deposito?: Prisma.SortOrder
  saldoCliente?: Prisma.SortOrder
}

export type WorkOrderMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  fecha?: Prisma.SortOrder
  horaSalida?: Prisma.SortOrder
  destino?: Prisma.SortOrder
  puntoEncuentro?: Prisma.SortOrder
  pasajeros?: Prisma.SortOrder
  detallesNotas?: Prisma.SortOrder
  combustible?: Prisma.SortOrder
  hielo?: Prisma.SortOrder
  aguaBebidas?: Prisma.SortOrder
  gastoVarios?: Prisma.SortOrder
  pagoCapitana?: Prisma.SortOrder
  pagoMarinero?: Prisma.SortOrder
  costoTotal?: Prisma.SortOrder
  deposito?: Prisma.SortOrder
  saldoCliente?: Prisma.SortOrder
}

export type WorkOrderMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  fecha?: Prisma.SortOrder
  horaSalida?: Prisma.SortOrder
  destino?: Prisma.SortOrder
  puntoEncuentro?: Prisma.SortOrder
  pasajeros?: Prisma.SortOrder
  detallesNotas?: Prisma.SortOrder
  combustible?: Prisma.SortOrder
  hielo?: Prisma.SortOrder
  aguaBebidas?: Prisma.SortOrder
  gastoVarios?: Prisma.SortOrder
  pagoCapitana?: Prisma.SortOrder
  pagoMarinero?: Prisma.SortOrder
  costoTotal?: Prisma.SortOrder
  deposito?: Prisma.SortOrder
  saldoCliente?: Prisma.SortOrder
}

export type WorkOrderSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pasajeros?: Prisma.SortOrder
  combustible?: Prisma.SortOrder
  hielo?: Prisma.SortOrder
  aguaBebidas?: Prisma.SortOrder
  gastoVarios?: Prisma.SortOrder
  pagoCapitana?: Prisma.SortOrder
  pagoMarinero?: Prisma.SortOrder
  costoTotal?: Prisma.SortOrder
  deposito?: Prisma.SortOrder
  saldoCliente?: Prisma.SortOrder
}

export type WorkOrderScalarRelationFilter = {
  is?: Prisma.WorkOrderWhereInput
  isNot?: Prisma.WorkOrderWhereInput
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableFloatFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type WorkOrderCreateNestedOneWithoutReceiptsInput = {
  create?: Prisma.XOR<Prisma.WorkOrderCreateWithoutReceiptsInput, Prisma.WorkOrderUncheckedCreateWithoutReceiptsInput>
  connectOrCreate?: Prisma.WorkOrderCreateOrConnectWithoutReceiptsInput
  connect?: Prisma.WorkOrderWhereUniqueInput
}

export type WorkOrderUpdateOneRequiredWithoutReceiptsNestedInput = {
  create?: Prisma.XOR<Prisma.WorkOrderCreateWithoutReceiptsInput, Prisma.WorkOrderUncheckedCreateWithoutReceiptsInput>
  connectOrCreate?: Prisma.WorkOrderCreateOrConnectWithoutReceiptsInput
  upsert?: Prisma.WorkOrderUpsertWithoutReceiptsInput
  connect?: Prisma.WorkOrderWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.WorkOrderUpdateToOneWithWhereWithoutReceiptsInput, Prisma.WorkOrderUpdateWithoutReceiptsInput>, Prisma.WorkOrderUncheckedUpdateWithoutReceiptsInput>
}

export type WorkOrderCreateWithoutReceiptsInput = {
  createdAt?: Date | string
  nombre: string
  fecha: Date | string
  horaSalida: string
  destino: string
  puntoEncuentro: string
  pasajeros: number
  detallesNotas?: string | null
  combustible?: number | null
  hielo?: number | null
  aguaBebidas?: number | null
  gastoVarios?: number | null
  pagoCapitana?: number | null
  pagoMarinero?: number | null
  costoTotal: number
  deposito?: number
  saldoCliente: number
}

export type WorkOrderUncheckedCreateWithoutReceiptsInput = {
  id?: number
  createdAt?: Date | string
  nombre: string
  fecha: Date | string
  horaSalida: string
  destino: string
  puntoEncuentro: string
  pasajeros: number
  detallesNotas?: string | null
  combustible?: number | null
  hielo?: number | null
  aguaBebidas?: number | null
  gastoVarios?: number | null
  pagoCapitana?: number | null
  pagoMarinero?: number | null
  costoTotal: number
  deposito?: number
  saldoCliente: number
}

export type WorkOrderCreateOrConnectWithoutReceiptsInput = {
  where: Prisma.WorkOrderWhereUniqueInput
  create: Prisma.XOR<Prisma.WorkOrderCreateWithoutReceiptsInput, Prisma.WorkOrderUncheckedCreateWithoutReceiptsInput>
}

export type WorkOrderUpsertWithoutReceiptsInput = {
  update: Prisma.XOR<Prisma.WorkOrderUpdateWithoutReceiptsInput, Prisma.WorkOrderUncheckedUpdateWithoutReceiptsInput>
  create: Prisma.XOR<Prisma.WorkOrderCreateWithoutReceiptsInput, Prisma.WorkOrderUncheckedCreateWithoutReceiptsInput>
  where?: Prisma.WorkOrderWhereInput
}

export type WorkOrderUpdateToOneWithWhereWithoutReceiptsInput = {
  where?: Prisma.WorkOrderWhereInput
  data: Prisma.XOR<Prisma.WorkOrderUpdateWithoutReceiptsInput, Prisma.WorkOrderUncheckedUpdateWithoutReceiptsInput>
}

export type WorkOrderUpdateWithoutReceiptsInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  fecha?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  horaSalida?: Prisma.StringFieldUpdateOperationsInput | string
  destino?: Prisma.StringFieldUpdateOperationsInput | string
  puntoEncuentro?: Prisma.StringFieldUpdateOperationsInput | string
  pasajeros?: Prisma.IntFieldUpdateOperationsInput | number
  detallesNotas?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  combustible?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  hielo?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  aguaBebidas?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  gastoVarios?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  pagoCapitana?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  pagoMarinero?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  costoTotal?: Prisma.FloatFieldUpdateOperationsInput | number
  deposito?: Prisma.FloatFieldUpdateOperationsInput | number
  saldoCliente?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type WorkOrderUncheckedUpdateWithoutReceiptsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  fecha?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  horaSalida?: Prisma.StringFieldUpdateOperationsInput | string
  destino?: Prisma.StringFieldUpdateOperationsInput | string
  puntoEncuentro?: Prisma.StringFieldUpdateOperationsInput | string
  pasajeros?: Prisma.IntFieldUpdateOperationsInput | number
  detallesNotas?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  combustible?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  hielo?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  aguaBebidas?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  gastoVarios?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  pagoCapitana?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  pagoMarinero?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  costoTotal?: Prisma.FloatFieldUpdateOperationsInput | number
  deposito?: Prisma.FloatFieldUpdateOperationsInput | number
  saldoCliente?: Prisma.FloatFieldUpdateOperationsInput | number
}


/**
 * Count Type WorkOrderCountOutputType
 */

export type WorkOrderCountOutputType = {
  receipts: number
}

export type WorkOrderCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  receipts?: boolean | WorkOrderCountOutputTypeCountReceiptsArgs
}

/**
 * WorkOrderCountOutputType without action
 */
export type WorkOrderCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkOrderCountOutputType
   */
  select?: Prisma.WorkOrderCountOutputTypeSelect<ExtArgs> | null
}

/**
 * WorkOrderCountOutputType without action
 */
export type WorkOrderCountOutputTypeCountReceiptsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReceiptWhereInput
}


export type WorkOrderSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  nombre?: boolean
  fecha?: boolean
  horaSalida?: boolean
  destino?: boolean
  puntoEncuentro?: boolean
  pasajeros?: boolean
  detallesNotas?: boolean
  combustible?: boolean
  hielo?: boolean
  aguaBebidas?: boolean
  gastoVarios?: boolean
  pagoCapitana?: boolean
  pagoMarinero?: boolean
  costoTotal?: boolean
  deposito?: boolean
  saldoCliente?: boolean
  receipts?: boolean | Prisma.WorkOrder$receiptsArgs<ExtArgs>
  _count?: boolean | Prisma.WorkOrderCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workOrder"]>

export type WorkOrderSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  nombre?: boolean
  fecha?: boolean
  horaSalida?: boolean
  destino?: boolean
  puntoEncuentro?: boolean
  pasajeros?: boolean
  detallesNotas?: boolean
  combustible?: boolean
  hielo?: boolean
  aguaBebidas?: boolean
  gastoVarios?: boolean
  pagoCapitana?: boolean
  pagoMarinero?: boolean
  costoTotal?: boolean
  deposito?: boolean
  saldoCliente?: boolean
}, ExtArgs["result"]["workOrder"]>

export type WorkOrderSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  nombre?: boolean
  fecha?: boolean
  horaSalida?: boolean
  destino?: boolean
  puntoEncuentro?: boolean
  pasajeros?: boolean
  detallesNotas?: boolean
  combustible?: boolean
  hielo?: boolean
  aguaBebidas?: boolean
  gastoVarios?: boolean
  pagoCapitana?: boolean
  pagoMarinero?: boolean
  costoTotal?: boolean
  deposito?: boolean
  saldoCliente?: boolean
}, ExtArgs["result"]["workOrder"]>

export type WorkOrderSelectScalar = {
  id?: boolean
  createdAt?: boolean
  nombre?: boolean
  fecha?: boolean
  horaSalida?: boolean
  destino?: boolean
  puntoEncuentro?: boolean
  pasajeros?: boolean
  detallesNotas?: boolean
  combustible?: boolean
  hielo?: boolean
  aguaBebidas?: boolean
  gastoVarios?: boolean
  pagoCapitana?: boolean
  pagoMarinero?: boolean
  costoTotal?: boolean
  deposito?: boolean
  saldoCliente?: boolean
}

export type WorkOrderOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "nombre" | "fecha" | "horaSalida" | "destino" | "puntoEncuentro" | "pasajeros" | "detallesNotas" | "combustible" | "hielo" | "aguaBebidas" | "gastoVarios" | "pagoCapitana" | "pagoMarinero" | "costoTotal" | "deposito" | "saldoCliente", ExtArgs["result"]["workOrder"]>
export type WorkOrderInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  receipts?: boolean | Prisma.WorkOrder$receiptsArgs<ExtArgs>
  _count?: boolean | Prisma.WorkOrderCountOutputTypeDefaultArgs<ExtArgs>
}
export type WorkOrderIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type WorkOrderIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $WorkOrderPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "WorkOrder"
  objects: {
    receipts: Prisma.$ReceiptPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    createdAt: Date
    nombre: string
    fecha: Date
    horaSalida: string
    destino: string
    puntoEncuentro: string
    pasajeros: number
    detallesNotas: string | null
    combustible: number | null
    hielo: number | null
    aguaBebidas: number | null
    gastoVarios: number | null
    pagoCapitana: number | null
    pagoMarinero: number | null
    costoTotal: number
    deposito: number
    saldoCliente: number
  }, ExtArgs["result"]["workOrder"]>
  composites: {}
}

export type WorkOrderGetPayload<S extends boolean | null | undefined | WorkOrderDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$WorkOrderPayload, S>

export type WorkOrderCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<WorkOrderFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: WorkOrderCountAggregateInputType | true
  }

export interface WorkOrderDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['WorkOrder'], meta: { name: 'WorkOrder' } }
  /**
   * Find zero or one WorkOrder that matches the filter.
   * @param {WorkOrderFindUniqueArgs} args - Arguments to find a WorkOrder
   * @example
   * // Get one WorkOrder
   * const workOrder = await prisma.workOrder.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WorkOrderFindUniqueArgs>(args: Prisma.SelectSubset<T, WorkOrderFindUniqueArgs<ExtArgs>>): Prisma.Prisma__WorkOrderClient<runtime.Types.Result.GetResult<Prisma.$WorkOrderPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one WorkOrder that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WorkOrderFindUniqueOrThrowArgs} args - Arguments to find a WorkOrder
   * @example
   * // Get one WorkOrder
   * const workOrder = await prisma.workOrder.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WorkOrderFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, WorkOrderFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkOrderClient<runtime.Types.Result.GetResult<Prisma.$WorkOrderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorkOrder that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkOrderFindFirstArgs} args - Arguments to find a WorkOrder
   * @example
   * // Get one WorkOrder
   * const workOrder = await prisma.workOrder.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WorkOrderFindFirstArgs>(args?: Prisma.SelectSubset<T, WorkOrderFindFirstArgs<ExtArgs>>): Prisma.Prisma__WorkOrderClient<runtime.Types.Result.GetResult<Prisma.$WorkOrderPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorkOrder that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkOrderFindFirstOrThrowArgs} args - Arguments to find a WorkOrder
   * @example
   * // Get one WorkOrder
   * const workOrder = await prisma.workOrder.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WorkOrderFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, WorkOrderFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkOrderClient<runtime.Types.Result.GetResult<Prisma.$WorkOrderPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more WorkOrders that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkOrderFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all WorkOrders
   * const workOrders = await prisma.workOrder.findMany()
   * 
   * // Get first 10 WorkOrders
   * const workOrders = await prisma.workOrder.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const workOrderWithIdOnly = await prisma.workOrder.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends WorkOrderFindManyArgs>(args?: Prisma.SelectSubset<T, WorkOrderFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkOrderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a WorkOrder.
   * @param {WorkOrderCreateArgs} args - Arguments to create a WorkOrder.
   * @example
   * // Create one WorkOrder
   * const WorkOrder = await prisma.workOrder.create({
   *   data: {
   *     // ... data to create a WorkOrder
   *   }
   * })
   * 
   */
  create<T extends WorkOrderCreateArgs>(args: Prisma.SelectSubset<T, WorkOrderCreateArgs<ExtArgs>>): Prisma.Prisma__WorkOrderClient<runtime.Types.Result.GetResult<Prisma.$WorkOrderPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many WorkOrders.
   * @param {WorkOrderCreateManyArgs} args - Arguments to create many WorkOrders.
   * @example
   * // Create many WorkOrders
   * const workOrder = await prisma.workOrder.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends WorkOrderCreateManyArgs>(args?: Prisma.SelectSubset<T, WorkOrderCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many WorkOrders and returns the data saved in the database.
   * @param {WorkOrderCreateManyAndReturnArgs} args - Arguments to create many WorkOrders.
   * @example
   * // Create many WorkOrders
   * const workOrder = await prisma.workOrder.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many WorkOrders and only return the `id`
   * const workOrderWithIdOnly = await prisma.workOrder.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends WorkOrderCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, WorkOrderCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkOrderPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a WorkOrder.
   * @param {WorkOrderDeleteArgs} args - Arguments to delete one WorkOrder.
   * @example
   * // Delete one WorkOrder
   * const WorkOrder = await prisma.workOrder.delete({
   *   where: {
   *     // ... filter to delete one WorkOrder
   *   }
   * })
   * 
   */
  delete<T extends WorkOrderDeleteArgs>(args: Prisma.SelectSubset<T, WorkOrderDeleteArgs<ExtArgs>>): Prisma.Prisma__WorkOrderClient<runtime.Types.Result.GetResult<Prisma.$WorkOrderPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one WorkOrder.
   * @param {WorkOrderUpdateArgs} args - Arguments to update one WorkOrder.
   * @example
   * // Update one WorkOrder
   * const workOrder = await prisma.workOrder.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends WorkOrderUpdateArgs>(args: Prisma.SelectSubset<T, WorkOrderUpdateArgs<ExtArgs>>): Prisma.Prisma__WorkOrderClient<runtime.Types.Result.GetResult<Prisma.$WorkOrderPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more WorkOrders.
   * @param {WorkOrderDeleteManyArgs} args - Arguments to filter WorkOrders to delete.
   * @example
   * // Delete a few WorkOrders
   * const { count } = await prisma.workOrder.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends WorkOrderDeleteManyArgs>(args?: Prisma.SelectSubset<T, WorkOrderDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorkOrders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkOrderUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many WorkOrders
   * const workOrder = await prisma.workOrder.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends WorkOrderUpdateManyArgs>(args: Prisma.SelectSubset<T, WorkOrderUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorkOrders and returns the data updated in the database.
   * @param {WorkOrderUpdateManyAndReturnArgs} args - Arguments to update many WorkOrders.
   * @example
   * // Update many WorkOrders
   * const workOrder = await prisma.workOrder.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more WorkOrders and only return the `id`
   * const workOrderWithIdOnly = await prisma.workOrder.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends WorkOrderUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, WorkOrderUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkOrderPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one WorkOrder.
   * @param {WorkOrderUpsertArgs} args - Arguments to update or create a WorkOrder.
   * @example
   * // Update or create a WorkOrder
   * const workOrder = await prisma.workOrder.upsert({
   *   create: {
   *     // ... data to create a WorkOrder
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the WorkOrder we want to update
   *   }
   * })
   */
  upsert<T extends WorkOrderUpsertArgs>(args: Prisma.SelectSubset<T, WorkOrderUpsertArgs<ExtArgs>>): Prisma.Prisma__WorkOrderClient<runtime.Types.Result.GetResult<Prisma.$WorkOrderPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of WorkOrders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkOrderCountArgs} args - Arguments to filter WorkOrders to count.
   * @example
   * // Count the number of WorkOrders
   * const count = await prisma.workOrder.count({
   *   where: {
   *     // ... the filter for the WorkOrders we want to count
   *   }
   * })
  **/
  count<T extends WorkOrderCountArgs>(
    args?: Prisma.Subset<T, WorkOrderCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WorkOrderCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a WorkOrder.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkOrderAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends WorkOrderAggregateArgs>(args: Prisma.Subset<T, WorkOrderAggregateArgs>): Prisma.PrismaPromise<GetWorkOrderAggregateType<T>>

  /**
   * Group by WorkOrder.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkOrderGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends WorkOrderGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WorkOrderGroupByArgs['orderBy'] }
      : { orderBy?: WorkOrderGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, WorkOrderGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWorkOrderGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the WorkOrder model
 */
readonly fields: WorkOrderFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for WorkOrder.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WorkOrderClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  receipts<T extends Prisma.WorkOrder$receiptsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WorkOrder$receiptsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReceiptPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the WorkOrder model
 */
export interface WorkOrderFieldRefs {
  readonly id: Prisma.FieldRef<"WorkOrder", 'Int'>
  readonly createdAt: Prisma.FieldRef<"WorkOrder", 'DateTime'>
  readonly nombre: Prisma.FieldRef<"WorkOrder", 'String'>
  readonly fecha: Prisma.FieldRef<"WorkOrder", 'DateTime'>
  readonly horaSalida: Prisma.FieldRef<"WorkOrder", 'String'>
  readonly destino: Prisma.FieldRef<"WorkOrder", 'String'>
  readonly puntoEncuentro: Prisma.FieldRef<"WorkOrder", 'String'>
  readonly pasajeros: Prisma.FieldRef<"WorkOrder", 'Int'>
  readonly detallesNotas: Prisma.FieldRef<"WorkOrder", 'String'>
  readonly combustible: Prisma.FieldRef<"WorkOrder", 'Float'>
  readonly hielo: Prisma.FieldRef<"WorkOrder", 'Float'>
  readonly aguaBebidas: Prisma.FieldRef<"WorkOrder", 'Float'>
  readonly gastoVarios: Prisma.FieldRef<"WorkOrder", 'Float'>
  readonly pagoCapitana: Prisma.FieldRef<"WorkOrder", 'Float'>
  readonly pagoMarinero: Prisma.FieldRef<"WorkOrder", 'Float'>
  readonly costoTotal: Prisma.FieldRef<"WorkOrder", 'Float'>
  readonly deposito: Prisma.FieldRef<"WorkOrder", 'Float'>
  readonly saldoCliente: Prisma.FieldRef<"WorkOrder", 'Float'>
}
    

// Custom InputTypes
/**
 * WorkOrder findUnique
 */
export type WorkOrderFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkOrder
   */
  select?: Prisma.WorkOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkOrder
   */
  omit?: Prisma.WorkOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkOrderInclude<ExtArgs> | null
  /**
   * Filter, which WorkOrder to fetch.
   */
  where: Prisma.WorkOrderWhereUniqueInput
}

/**
 * WorkOrder findUniqueOrThrow
 */
export type WorkOrderFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkOrder
   */
  select?: Prisma.WorkOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkOrder
   */
  omit?: Prisma.WorkOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkOrderInclude<ExtArgs> | null
  /**
   * Filter, which WorkOrder to fetch.
   */
  where: Prisma.WorkOrderWhereUniqueInput
}

/**
 * WorkOrder findFirst
 */
export type WorkOrderFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkOrder
   */
  select?: Prisma.WorkOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkOrder
   */
  omit?: Prisma.WorkOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkOrderInclude<ExtArgs> | null
  /**
   * Filter, which WorkOrder to fetch.
   */
  where?: Prisma.WorkOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkOrders to fetch.
   */
  orderBy?: Prisma.WorkOrderOrderByWithRelationInput | Prisma.WorkOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorkOrders.
   */
  cursor?: Prisma.WorkOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkOrders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkOrders.
   */
  distinct?: Prisma.WorkOrderScalarFieldEnum | Prisma.WorkOrderScalarFieldEnum[]
}

/**
 * WorkOrder findFirstOrThrow
 */
export type WorkOrderFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkOrder
   */
  select?: Prisma.WorkOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkOrder
   */
  omit?: Prisma.WorkOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkOrderInclude<ExtArgs> | null
  /**
   * Filter, which WorkOrder to fetch.
   */
  where?: Prisma.WorkOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkOrders to fetch.
   */
  orderBy?: Prisma.WorkOrderOrderByWithRelationInput | Prisma.WorkOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorkOrders.
   */
  cursor?: Prisma.WorkOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkOrders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkOrders.
   */
  distinct?: Prisma.WorkOrderScalarFieldEnum | Prisma.WorkOrderScalarFieldEnum[]
}

/**
 * WorkOrder findMany
 */
export type WorkOrderFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkOrder
   */
  select?: Prisma.WorkOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkOrder
   */
  omit?: Prisma.WorkOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkOrderInclude<ExtArgs> | null
  /**
   * Filter, which WorkOrders to fetch.
   */
  where?: Prisma.WorkOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkOrders to fetch.
   */
  orderBy?: Prisma.WorkOrderOrderByWithRelationInput | Prisma.WorkOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing WorkOrders.
   */
  cursor?: Prisma.WorkOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkOrders.
   */
  skip?: number
  distinct?: Prisma.WorkOrderScalarFieldEnum | Prisma.WorkOrderScalarFieldEnum[]
}

/**
 * WorkOrder create
 */
export type WorkOrderCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkOrder
   */
  select?: Prisma.WorkOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkOrder
   */
  omit?: Prisma.WorkOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkOrderInclude<ExtArgs> | null
  /**
   * The data needed to create a WorkOrder.
   */
  data: Prisma.XOR<Prisma.WorkOrderCreateInput, Prisma.WorkOrderUncheckedCreateInput>
}

/**
 * WorkOrder createMany
 */
export type WorkOrderCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many WorkOrders.
   */
  data: Prisma.WorkOrderCreateManyInput | Prisma.WorkOrderCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * WorkOrder createManyAndReturn
 */
export type WorkOrderCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkOrder
   */
  select?: Prisma.WorkOrderSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorkOrder
   */
  omit?: Prisma.WorkOrderOmit<ExtArgs> | null
  /**
   * The data used to create many WorkOrders.
   */
  data: Prisma.WorkOrderCreateManyInput | Prisma.WorkOrderCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * WorkOrder update
 */
export type WorkOrderUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkOrder
   */
  select?: Prisma.WorkOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkOrder
   */
  omit?: Prisma.WorkOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkOrderInclude<ExtArgs> | null
  /**
   * The data needed to update a WorkOrder.
   */
  data: Prisma.XOR<Prisma.WorkOrderUpdateInput, Prisma.WorkOrderUncheckedUpdateInput>
  /**
   * Choose, which WorkOrder to update.
   */
  where: Prisma.WorkOrderWhereUniqueInput
}

/**
 * WorkOrder updateMany
 */
export type WorkOrderUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update WorkOrders.
   */
  data: Prisma.XOR<Prisma.WorkOrderUpdateManyMutationInput, Prisma.WorkOrderUncheckedUpdateManyInput>
  /**
   * Filter which WorkOrders to update
   */
  where?: Prisma.WorkOrderWhereInput
  /**
   * Limit how many WorkOrders to update.
   */
  limit?: number
}

/**
 * WorkOrder updateManyAndReturn
 */
export type WorkOrderUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkOrder
   */
  select?: Prisma.WorkOrderSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorkOrder
   */
  omit?: Prisma.WorkOrderOmit<ExtArgs> | null
  /**
   * The data used to update WorkOrders.
   */
  data: Prisma.XOR<Prisma.WorkOrderUpdateManyMutationInput, Prisma.WorkOrderUncheckedUpdateManyInput>
  /**
   * Filter which WorkOrders to update
   */
  where?: Prisma.WorkOrderWhereInput
  /**
   * Limit how many WorkOrders to update.
   */
  limit?: number
}

/**
 * WorkOrder upsert
 */
export type WorkOrderUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkOrder
   */
  select?: Prisma.WorkOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkOrder
   */
  omit?: Prisma.WorkOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkOrderInclude<ExtArgs> | null
  /**
   * The filter to search for the WorkOrder to update in case it exists.
   */
  where: Prisma.WorkOrderWhereUniqueInput
  /**
   * In case the WorkOrder found by the `where` argument doesn't exist, create a new WorkOrder with this data.
   */
  create: Prisma.XOR<Prisma.WorkOrderCreateInput, Prisma.WorkOrderUncheckedCreateInput>
  /**
   * In case the WorkOrder was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.WorkOrderUpdateInput, Prisma.WorkOrderUncheckedUpdateInput>
}

/**
 * WorkOrder delete
 */
export type WorkOrderDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkOrder
   */
  select?: Prisma.WorkOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkOrder
   */
  omit?: Prisma.WorkOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkOrderInclude<ExtArgs> | null
  /**
   * Filter which WorkOrder to delete.
   */
  where: Prisma.WorkOrderWhereUniqueInput
}

/**
 * WorkOrder deleteMany
 */
export type WorkOrderDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorkOrders to delete
   */
  where?: Prisma.WorkOrderWhereInput
  /**
   * Limit how many WorkOrders to delete.
   */
  limit?: number
}

/**
 * WorkOrder.receipts
 */
export type WorkOrder$receiptsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Receipt
   */
  select?: Prisma.ReceiptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Receipt
   */
  omit?: Prisma.ReceiptOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReceiptInclude<ExtArgs> | null
  where?: Prisma.ReceiptWhereInput
  orderBy?: Prisma.ReceiptOrderByWithRelationInput | Prisma.ReceiptOrderByWithRelationInput[]
  cursor?: Prisma.ReceiptWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ReceiptScalarFieldEnum | Prisma.ReceiptScalarFieldEnum[]
}

/**
 * WorkOrder without action
 */
export type WorkOrderDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkOrder
   */
  select?: Prisma.WorkOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkOrder
   */
  omit?: Prisma.WorkOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkOrderInclude<ExtArgs> | null
}
